---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/python.yml
  - project: invenia/gitlab-ci-helper
    file: /templates/py-check.yml
  - project: invenia/gitlab-ci-helper
    file: /templates/teardown.yml

# py-check.yml will include "Code Format Check", and "Version Check"
# teardown.yml will include "Coverage", "Documentation", and "pages"

"Upload to Private PyPI":
  extends: .upload_to_private_pypi

"Test Docker Build (Linux 64-Bit)":
  stage: test
  tags:
    - amzn2
    - docker-build
  before_script:
    - echo "$common_functions" > common && source common
    - enter_python_venv
    - sudo yum -y install gcc git
    - pip install tox
    - docker --version
  script:
    - tox -e py38
    - deactivate
